when:
  - event: pull_request
  - event: push
    branch: main

labels:
  platform: linux/amd64

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      lfs: false
      depth: 1

steps:
  build-jdk-8:
    image: maven:3.9-eclipse-temurin-8
    commands:
      - mvn -B -DskipTests clean verify

  build-jdk-17:
    image: maven:3.9-eclipse-temurin-17
    commands:
      - mvn -B -DskipTests clean verify

  build-jdk-21:
    image: maven:3.9-eclipse-temurin-21
    commands:
      - mvn -B -DskipTests clean verify
