name: Release Java SDK to Maven Central

on:
  pull_request:
    branches: ['main']


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

# echo secrets 
      - name: Echo secrets
        run: |
          echo ${{ secrets.MAVEN_USERNAME }}
          echo ${{ secrets.MAVEN_PASSWORD }}
          echo ${{ secrets.GPG_PASSPHRASE }}
          echo ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}


      # - name: Set Maven Version
      #   run: mvn versions:set -DnewVersion=${{ github.event.inputs.newVersion }}

      # - name: Commit new version
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git commit -am "Update project version to ${{ github.event.inputs.newVersion }}"
      #     git push

      - name: Deploy to Maven Central
        run: mvn clean deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
