name: Release Java SDK to Maven Central

on:
  pull_request:
    branches: ['main']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # - name: Decode GPG Key
      #   run: |
      #     echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > ${{ github.workspace }}/gpg_key.asc

      
      # - name: Display encoded key format (Debugging only - do not use in production)
      #   run: cat ${{ github.workspace }}/gpg_key.asc

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          delete_private_key: true

      - name: Deploy to Maven Central
        run: mvn clean deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
